package org.libre.search.search

import org.libre.search.core.Prefs
import org.libre.search.core.Text

object ResultFilter {

    /** Sites whose images are mostly or entirely AI-generated. */
    private val aiImageDomains = listOf(
        "lexica.art", "civitai.com", "openart.ai", "nightcafe.studio", "creator.nightcafe.studio",
        "playgroundai.com", "playground.com", "midjourney.com", "craiyon.com", "starryai.com",
        "pixai.art", "tensor.art", "seaart.ai", "getimg.ai", "leonardo.ai", "dreamstudio.ai",
        "stablediffusionweb.com", "aiartists.org", "prompthero.com", "arthub.ai", "mage.space",
        "dezgo.com", "neural.love", "hotpot.ai", "deepai.org", "dreamlike.art", "promptbase.com",
        "ideogram.ai", "krea.ai", "imagine.art",
        "aigallery.app", "aiimagegenerator.org", "yodayo.com", "novelai.net", "perchance.org",
        "artbreeder.com", "wombo.art", "dream.ai", "starryai.app", "freeflo.ai", "lummi.ai",
        "stockcake.com", "gencraft.com", "clipdrop.co", "firefly.adobe.com",
    )

    private val aiWords = listOf(
        "ai generated", "ai-generated", "ai art", "ai image", "generated by ai", "generative ai",
        "midjourney", "stable diffusion", "stablediffusion", "dall-e", "dall·e", "dalle", "sdxl",
        "flux.1", "généré par ia", "généré par l'ia", "image ia", "créée par ia", "illustration ia",
        "ai illustration", "ai artwork", "ai-art", "made with ai", "created with ai", "ai wallpaper",
    )

    private val aiPathHints = listOf("bing.com/images/create", "/ai-generated", "/ai-image", "/ai-art", "/free-photos-vectors/ai-", "-ai-generated", "ai-generated-")

    /** Israeli outlets and pro-Israel advocacy media (hidden from web results when enabled). */
    val israeliOutlets = listOf(
        "timesofisrael.com", "jpost.com", "haaretz.com", "haaretz.co.il", "ynetnews.com", "ynet.co.il",
        "i24news.tv", "israelhayom.com", "israelhayom.co.il", "israelnationalnews.com", "jns.org",
        "maariv.co.il", "globes.co.il", "kan.org.il", "calcalistech.com", "calcalist.co.il", "walla.co.il",
        "mako.co.il", "n12.co.il", "c14.co.il", "allisrael.com", "algemeiner.com", "honestreporting.com",
        "camera.org", "jewishpress.com", "israel21c.org", "tabletmag.com", "unitedwithisrael.org",
        "jforum.fr", "israelvalley.com", "coolamnews.com", "europe-israel.org", "tribunejuive.info",
        "dreuz.info", "lphinfo.com", "timesofisrael.fr", "fr.timesofisrael.com", "i24news.tv/fr",
    )

    fun isAiImage(img: ImageResult): Boolean {
        val host = Text.host(img.pageUrl)
        val imgHost = Text.host(img.imageUrl)
        if (aiImageDomains.any { Text.hostMatches(host, it) || Text.hostMatches(imgHost, it) }) return true
        val t = img.title.lowercase()
        if (aiWords.any { t.contains(it) }) return true
        val u = (img.pageUrl + " " + img.imageUrl).lowercase()
        if (aiPathHints.any { u.contains(it) }) return true
        return false
    }

    fun isAiVideo(v: VideoResult): Boolean {
        val t = v.title.lowercase()
        return listOf("ai generated", "ai-generated", "sora ", "veo 3", "made with ai", "généré par ia").any { t.contains(it) }
    }

    fun blocked(url: String): Boolean {
        val host = Text.host(url)
        if (host.isEmpty()) return false
        if (Prefs.blockedDomains.any { Text.hostMatches(host, it) }) return true
        if (Prefs.hideIsraeliOutlets && israeliOutlets.any { Text.hostMatches(host, it.substringBefore('/')) }) return true
        return false
    }

    fun web(list: List<WebResult>) = list.filterNot { blocked(it.url) }
    fun videos(list: List<VideoResult>) = list.filterNot { blocked(it.url) || (Prefs.hideAiImages && isAiVideo(it)) }
    fun discussions(list: List<Discussion>) = list.filterNot { blocked(it.url) }
    fun images(list: List<ImageResult>) = list.filterNot {
        blocked(it.pageUrl) || (Prefs.hideAiImages && isAiImage(it))
    }
}
